### ISSUE TITLE
Bump version to 1.0.0

### ISSUE THREAD

**Issue by jakedipity** [s-yadav/FlakeId#7]
Is this module stable? Would it be appropriate to bump the major version to 1.0.0?

**Comment by s-yadav** [comment]
I guess it's stable. I used it long back on a production site, and it worked fine there. Not sure if anyone is facing any issue on this.

**Comment by jakedipity** [comment]
I also use it in production and have never really thought about it until someone pointed it out. To them, at a glance, they were worried this module could not be trusted since technically it was still on the "unstable 0.x.x" version.

**Comment by s-yadav** [comment]
I tested it again. And I see that it is working properly there was one dependency missing though. Fixed it. 
I have made v1.0.0 release with the fixes.

**Comment by s-yadav** [comment]
Closing this. Let me know if you face any issue with the module.
