### ISSUE TITLE
Optionally Return BigInt

### ISSUE THREAD

**Issue by mkadirtan** [s-yadav/FlakeId#8]
It would be great to have a bigint return type if user wants to. It is not possible for me to cast integer from id.gen() to bigint in mongodb.

**Comment by s-yadav** [comment]
Isn't BigInt constructor helpful.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by mkadirtan** [comment]
Actually I had trouble understanding underlying algorithm, and at first I thought hexToDec doesn't return exact result. So yeah, bigint constructor is good, thanks!
